### ISSUE TITLE
How do I removeEventListener?

### ISSUE THREAD

**Issue by iwata** [mya-ake/vue-window-size#1]
Thank you for making useful libraries.

By the way, when trying to use this library as mixin, I'd like to `removeEventListener` on `beforeDestroy`.
Are you planning to provide such an API or are there any other workarounds for event leaks?

**Comment by mya-ake** [comment]
@iwata 

Thunk you, question.
This library will only addEventListener one time even if it is used in mixin.
We add that to the README. And I will make a public api for addition and deletion.

**Comment by mya-ake** [comment]
@iwata 

I released destroy method. And added that to the README.
https://github.com/mya-ake/vue-window-size/releases/tag/v0.2.0

So close the issue. 
If you have something else please give me an issue. Thank you.

**Comment by iwata** [comment]
I appreciate your prompt attention!
