### ISSUE TITLE
peer dep missing: @vue/composition-api@^1.0.0-beta.14, required by vue-window-size@1.0.2

### ISSUE THREAD

**Issue by Oleksii14** [mya-ake/vue-window-size#223]
While installing a package for Vue 3 project, I receive npm warnings:

peer dep missing: @vue/composition-api@^1.0.0-beta.14, required by vue-window-size@1.0.2
peer dep missing: @vue/composition-api@>=1.0.0-beta.1, required by vue-demi@0.4.1

Why does this package depend on `@vue/composition-api`?

**Comment by mya-ake** [comment]
`@vue/composition-api` is also included in peer dep as it also supports vue 2.
If you're using vue 3, you can safely ignore the warning.
