### ISSUE TITLE
When Window on Max, The width or height not refresh!

### ISSUE THREAD

**Issue by MoConWu** [mya-ake/vue-window-size#422]
When Window on Max, The width or height not refresh!

**Comment by mya-ake** [comment]
@MoConWu 
Thank you for the issue.
I tried it in chrome, and it seems to refresh. Let me ask you a few questions.

> When Window on Max
Is it when you maximize the browser? If possible, I would like you to take a video of how you performed the operation.

What browsers does it occur in?

What version of vue and vue-window-size are you using?

**Comment by MoConWu** [comment]
> @MoConWu 
> Thank you for the issue.
> I tried it in chrome, and it seems to refresh. Let me ask you a few questions.
> 
> > When Window on Max
> 
> Is it when you maximize the browser? If possible, I would like you to take a video of how you performed the operation.
> 
> What browsers does it occur in?
> 
> What version of vue and vue-window-size are you using?


Thank you.

I use it on electron v17.0.0 (lastest) project.

when electron window resizing, the value is changing, but when I max the window or recovery window size, the vlaue is not change.

**Comment by MoConWu** [comment]
I found that the scrollbar did not refresh the size, not the value refresh.
