### ISSUE TITLE
Update to Vue 2.7.10 fails due to mismatch of Vue Window Size dependency

### ISSUE THREAD

**Issue by Kenvdb** [mya-ake/vue-window-size#429]
I'm have troubles updating Vue from 2.6 to 2.7.10, it looks like there is a mismatch with Vue Window Size.

```
npm ERR! Found: vue@2.7.10
npm ERR! node_modules/vue
npm ERR!   vue@"^2.7.10" from the root project
npm ERR!   peer vue@"^2.6.0 || >=3.0.0" from vue-window-size@1.0.0-6
npm ERR!   node_modules/vue-window-size
npm ERR!     vue-window-size@"1.0.0-6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.0
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.0.0-beta.14" from vue-window-size@1.0.0-6
npm ERR!   node_modules/vue-window-size
npm ERR!     vue-window-size@"1.0.0-6" from the root project
```

For what I understand is that Vue 2.7.10 doesn't need the **@vue/composition-api** dependency. Therefor the sentence **Could not resolve dependency** shouldn't be a problem imho. I've tried to use Vue Window Size versions **1.0.6** and **1.1.2**, unfortunately both results in the same error?

Reason to update to Vue 2.7.10 is an vulnerability in another package which is being used in the application, which therefor needs to be updated to the latest version, which also needs Vue 2.7.10.

Thanks for your help in advance!

**Comment by mya-ake** [comment]
Thanks for the report! I'll check this.

**Comment by Kenvdb** [comment]
Great work @mya-ake 

Could you please let me know what version of **vue-window-size** I need in my setup to get it working again?

**Comment by mya-ake** [comment]
@Kenvdb 
I fixed this. Please use **vue-window-size@1.0.8** 👍

**Comment by Kenvdb** [comment]
Awesome, quick response and fix. Very much appreciated.

**Comment by mya-ake** [comment]
You're welcome!
Once the problem has been resolved, please close this issue.
